language: node_js
matrix:
  include:
    - node_js: "6"
      script: "npm test"
      after_success: "nyc report --reporter=text-lcov | coveralls"
    - node_js: "6"
      script: "yarn test"
    - node_js: "8"
      script: "npm test"